# Site settings
title: Jason Anton
email: jason@conversadocs.com
description: Jason offers top-notch software development consulting specializing in AI & ML operations and development. Elevate your projects with expert guidance. # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.jasonanton.com" # the base hostname & protocol for your site
tagline: The Digital Janitor.

linkedin_username: stoopidjson
github_username: stoopidJSON

analytics: G-NG62FKMR80

compress-site: yes

encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development

# Build settings
markdown: kramdown

social:
  name: Ben Balter
  links:
    - https://www.linkedin.com/in/stoopidjson
    - https://github.com/stoopidJSON
    - https://bsky.app/profile/stoopidjson.bsky.social
